### ISSUE TITLE
OSCHub Documentation

### ISSUE THREAD

**Issue by dat-adi** [Open-Source-Community-VIT-AP/oschub#48]
## Why do we have this issue?
The Documentation for OSCHub has not been given a thought throughout the course of building the project. However, it will be essential in the case that the project is to be made public.

The docs that are to be added, are regarding each application and should preferably be made by the person who was in charge of the feature.

## Contributors
The initial contributors to each of the features are,
Front End => @Sudhee-bsp 
Back End => @bhargavd2 
DB & End => @kode-logger

**Comment by kode-logger** [comment]
The first version of documentation is live at oschub wiki page, it covers most of the topics that are necessary to understand oschub and it's working.

The documentation includes three pages:

1. User manual
2. Developer manual
3. Admin manual

However, further updates will be made as time withers away.

**Comment by dat-adi** [comment]
@all-contributors please add @dat-adi for design, doc, mentoring and projectManagement.

**Comment by dat-adi** [comment]
@all-contributors please add @dat-adi for design, doc, mentoring and projectManagement.
@all-contributors please add @bhargavd2 for code, bugs, and documentation.
@all-contributors please add @Sudhee-bsp for design, bugs, and code.
@all-contributors please add @kode-logger for bugs, documentation, code, and maintenance.

**Comment by dat-adi** [comment]
@all-contributors please add @kode-logger for doc, bugs, code, and maintenance.
