### ISSUE TITLE
Hosting the application online

### ISSUE THREAD

**Issue by SVijayB** [Open-Source-Community-VIT-AP/oschub#51]
**Describe the solution you'd like**
Hosting the application online for everyone to use. 
Currently working on Heroku.

**Describe alternatives you've considered**
None so far.

**Comment by SVijayB** [comment]
Got it running right now at https://osc-hub.herokuapp.com/.
Test it out and let me know of changes.

Currently pushed changes by making db.sqlite3 public by removing it from gitignore, then pushing changes to Heroku using CLI.

Fix: Creating a private repo and saving creds and DB and using this to deploy it to the cloud.

**Comment by SVijayB** [comment]
Alright, so currently facing an IntegrityError while logging in.
This however does not seem to be the case for my account, weird since I hadn't set up anything using my Email ID.
Attached below is the screenshot of the error.

![Integrity error](https://user-images.githubusercontent.com/54742586/115102349-f1140100-9f67-11eb-81ef-b50b204f22fc.jpeg)

**Comment by dat-adi** [comment]
This issue has been fixed to my knowledge, with the latest commit 9b89ae36a0d3ce6e3a18b76aaf7a37fe55e0efe3.

**Comment by SVijayB** [comment]
Fixed at 9b89ae36a0d3ce6e3a18b76aaf7a37fe55e0efe3.

Hosting completed using Heroku.

Things to remember while deploying to heroku:
- Remove db.sqlite3 from .gitignore.
- git add -A
- git commit -m "message"
- git push heroku master
- git reset --hard HEAD~1 (In order to prevent the previous commit from showing up on our Git History)

And that's it.

**Comment by SVijayB** [comment]
Ignore the above message. Connected DB to PostgreSQL and enabled CI with GitHub. Pushes made to the master branch will automatically be deployed on Heroku. 😄 💯

**Comment by dat-adi** [comment]
@all-contributors please add @SVijayB for infrastructure.
