### ISSUE TITLE
Building an API for Credit Analysis Integration

### ISSUE THREAD

**Issue by dat-adi** [Open-Source-Community-VIT-AP/oschub#52]
**Is your feature request related to a problem? Please describe.**
There is an ongoing discussion on the potential development of a credit analysis software on the [osc-eb repository](https://github.com/Open-Source-Community-VIT-AP/osc-eb/issues/2).
In order for the data of each user on OSCHub to be sent for credit analysis, we will require a method, may it be REST APIs, or a simple connection to the Sheets API with an indexing for each participant.

**Describe the solution you'd like**
Look into the features and potential upgrades that can be made in order to build an API that would allow for Data to be sent from OSCHub with the least number of issues and good scalability.

**Describe alternatives you've considered**
Alternatives that have been considered are a script that parses the data that we have stored on Google Sheets rather than OSCHub.

**Comment by SVijayB** [comment]
Adding on to the above points, just send back json data upon get request -> collect the "Attended list" and send it back as json.
Rest can be worked on and calculated directly from the other end.

However....
This can be entirely ignored. Considering that we can retrieve required data from the remote database directly (contact me or @dat-adi for access details), this process becomes redundant. 
All this can be directly performed in [OSCLab](https://github.com/Open-Source-Community-VIT-AP/OSCLab) is what I mean.

**Comment by dat-adi** [comment]
Considering that, it would perhaps be a good idea to implement a script that updates the Sheet location of the  `Event Data` for each event, into another Google Sheet, adding this function to the SheetMe update hook.

This sheet can be accessed by OSCLab as well, providing all the required links to the updated data.

**Comment by SVijayB** [comment]
I don't get it, is there any particular reason why we should do that? 
I mean considering we extract data from the db directly, we can make OSCLab work dynamically for each participant, the moment they enroll on an event on OSCHub, their details get updated on OSCLab. I don't think that's how it works when we use spreadsheets to update data. Correct me if I am wrong.

**Comment by dat-adi** [comment]
Ah, your previous point required elaboration. It makes sense now.
Valid, seems like there's no requirement for a API/Script in order to extract data.
Closing issue.
