### ISSUE TITLE
The carousel in the speaker's section is not working

### ISSUE THREAD

**Issue by saipranay47** [Open-Source-Community-VIT-AP/oschub#59]
The carousel in the speaker's section is not working

![image](https://user-images.githubusercontent.com/70259716/126131142-151bd484-6ad0-42b4-9fa5-d502ee100bca.png)

**Comment by dat-adi** [comment]
For more information regarding the bug.
The carousel does not work until there are atleast 4 speakers in the present in the Speakers Model.

The issue has to do with an incorrect implementation of JavaScript, and should mostly be contained in the [Speakers](https://github.com/Open-Source-Community-VIT-AP/oschub/blob/master/dashboard/templates/dashboard/speakers.html).
