### ISSUE TITLE
Concealing events from user

### ISSUE THREAD

**Issue by kode-logger** [Open-Source-Community-VIT-AP/oschub#74]
**Is your feature request related to a problem? Please describe.**
Whenever a new event is added to OSCHub, it is available to all the users publicly. Due to this, testing an event before going live is not possible and it doesn't seem like a good idea to reveal test events live.

**Describe the solution you'd like**
By adding a new Boolean parameter (something like `isPublic`) to the database, we can check whether the value is true or false. 

If true then 
- The event will be visible to everyone 
 
Else
- The event  will be only visible to the admin moderators.

**Describe alternatives you've considered**
None

**Additional context**
This can be achieved by adding some control statements to the backend and creating a new attribute in the database table.

**Comment by SVijayB** [comment]
I honestly think we should create a development environment to test out events.

**Comment by SVijayB** [comment]
Closing this issue upon discussing with @kode-logger.
